//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlatFXResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlatFXResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name.
        /// </summary>
        public static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        public static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Description.
        /// </summary>
        public static string ActionDescription {
            get {
                return ResourceManager.GetString("ActionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Manage.
        /// </summary>
        public static string AdminManage {
            get {
                return ResourceManager.GetString("AdminManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Amount.
        /// </summary>
        public static string AllAmount {
            get {
                return ResourceManager.GetString("AllAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow to trade directlly.
        /// </summary>
        public static string AllowToTradeDirectlly {
            get {
                return ResourceManager.GetString("AllowToTradeDirectlly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount range.
        /// </summary>
        public static string AmountRange {
            get {
                return ResourceManager.GetString("AmountRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved by FlatFX.
        /// </summary>
        public static string ApprovedBYFlatFX {
            get {
                return ResourceManager.GetString("ApprovedBYFlatFX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved by provider.
        /// </summary>
        public static string ApprovedBYProvider {
            get {
                return ResourceManager.GetString("ApprovedBYProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as soon as possible and no later than.
        /// </summary>
        public static string ASAP {
            get {
                return ResourceManager.GetString("ASAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        public static string At {
            get {
                return ResourceManager.GetString("At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUD - ILS ($-₪).
        /// </summary>
        public static string AUDILS {
            get {
                return ResourceManager.GetString("AUDILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back to your account.
        /// </summary>
        public static string backtoyouraccount {
            get {
                return ResourceManager.GetString("backtoyouraccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        public static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account.
        /// </summary>
        public static string BankAccount {
            get {
                return ResourceManager.GetString("BankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank account details.
        /// </summary>
        public static string BankAccountDetails {
            get {
                return ResourceManager.GetString("BankAccountDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank account name.
        /// </summary>
        public static string BankAccountName {
            get {
                return ResourceManager.GetString("BankAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange amount (Million $).
        /// </summary>
        public static string BankCommission1 {
            get {
                return ResourceManager.GetString("BankCommission1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange commission discount (0%-100%).
        /// </summary>
        public static string BankCommission2 {
            get {
                return ResourceManager.GetString("BankCommission2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spread discount (0%-100%).
        /// </summary>
        public static string BankCommission3 {
            get {
                return ResourceManager.GetString("BankCommission3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Bank commission.
        /// </summary>
        public static string BankCommission4 {
            get {
                return ResourceManager.GetString("BankCommission4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving with FlatFX.
        /// </summary>
        public static string BankCommission5 {
            get {
                return ResourceManager.GetString("BankCommission5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlatFX commission.
        /// </summary>
        public static string BankCommission6 {
            get {
                return ResourceManager.GetString("BankCommission6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank commission calculator.
        /// </summary>
        public static string BankCommissionHeader {
            get {
                return ResourceManager.GetString("BankCommissionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank commission without discount is 0.2%.
        /// </summary>
        public static string BankCommissionRemark1 {
            get {
                return ResourceManager.GetString("BankCommissionRemark1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank spread without discount is 0.9%.
        /// </summary>
        public static string BankCommissionRemark2 {
            get {
                return ResourceManager.GetString("BankCommissionRemark2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * The bank commission without discount is 1.1%..
        /// </summary>
        public static string BankSpreadIs {
            get {
                return ResourceManager.GetString("BankSpreadIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Number.
        /// </summary>
        public static string BranchNumber {
            get {
                return ResourceManager.GetString("BranchNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string Buy2 {
            get {
                return ResourceManager.GetString("Buy2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Amount (you receive).
        /// </summary>
        public static string BuyAmount {
            get {
                return ResourceManager.GetString("BuyAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Buying.
        /// </summary>
        public static string ByBuying {
            get {
                return ResourceManager.GetString("ByBuying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Selling.
        /// </summary>
        public static string BySelling {
            get {
                return ResourceManager.GetString("BySelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Phone.
        /// </summary>
        public static string CarPhone {
            get {
                return ResourceManager.GetString("CarPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHF - ILS (CHF-₪).
        /// </summary>
        public static string CHFILS {
            get {
                return ResourceManager.GetString("CHFILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Fields.
        /// </summary>
        public static string CommissionCalcAdmin1 {
            get {
                return ResourceManager.GetString("CommissionCalcAdmin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlatFX commission (Promil):.
        /// </summary>
        public static string CommissionCalcAdmin2 {
            get {
                return ResourceManager.GetString("CommissionCalcAdmin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank commission (Promil):.
        /// </summary>
        public static string CommissionCalcAdmin3 {
            get {
                return ResourceManager.GetString("CommissionCalcAdmin3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlatFX income:.
        /// </summary>
        public static string CommissionCalcAdmin4 {
            get {
                return ResourceManager.GetString("CommissionCalcAdmin4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        public static string Companies {
            get {
                return ResourceManager.GetString("Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Accounts.
        /// </summary>
        public static string CompanyAccounts {
            get {
                return ResourceManager.GetString("CompanyAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string CompanyFullName {
            get {
                return ResourceManager.GetString("CompanyFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company joining code.
        /// </summary>
        public static string CompanyJoiningCode {
            get {
                return ResourceManager.GetString("CompanyJoiningCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In case you wish to join to existing company, you should get a code from the company administrator that enable you to join the company. Enter this code here.
        /// </summary>
        public static string CompanyJoiningCodeDescrition {
            get {
                return ResourceManager.GetString("CompanyJoiningCodeDescrition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Volume (yearly, USD).
        /// </summary>
        public static string CompanyVolumePerYearUSD {
            get {
                return ResourceManager.GetString("CompanyVolumePerYearUSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmationNumber.
        /// </summary>
        public static string ConfirmationNumber {
            get {
                return ResourceManager.GetString("ConfirmationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your Deal.
        /// </summary>
        public static string ConfirmYourDeal {
            get {
                return ResourceManager.GetString("ConfirmYourDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your DEMO Deal.
        /// </summary>
        public static string ConfirmYourDEMODeal {
            get {
                return ResourceManager.GetString("ConfirmYourDEMODeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your DEMO Order.
        /// </summary>
        public static string ConfirmYourDEMOOrder {
            get {
                return ResourceManager.GetString("ConfirmYourDEMOOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your Order.
        /// </summary>
        public static string ConfirmYourOrder {
            get {
                return ResourceManager.GetString("ConfirmYourOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Details.
        /// </summary>
        public static string ContactDetails {
            get {
                return ResourceManager.GetString("ContactDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co-Worker Email.
        /// </summary>
        public static string CoWorkerEmail {
            get {
                return ResourceManager.GetString("CoWorkerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created At.
        /// </summary>
        public static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Demo account.
        /// </summary>
        public static string CreateDemoAccount {
            get {
                return ResourceManager.GetString("CreateDemoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Demo User.
        /// </summary>
        public static string CreateDemoUser {
            get {
                return ResourceManager.GetString("CreateDemoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new account group.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new company.
        /// </summary>
        public static string CreateNewCompany {
            get {
                return ResourceManager.GetString("CreateNewCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Expired, Create a new Order.
        /// </summary>
        public static string CreateNewOrder {
            get {
                return ResourceManager.GetString("CreateNewOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new user.
        /// </summary>
        public static string CreateNewUser {
            get {
                return ResourceManager.GetString("CreateNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Exchange rates indication.
        /// </summary>
        public static string CurrencyExchangeRateIndication {
            get {
                return ResourceManager.GetString("CurrencyExchangeRateIndication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Type.
        /// </summary>
        public static string CustomerType {
            get {
                return ResourceManager.GetString("CustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily P&amp;L.
        /// </summary>
        public static string DailyPNL {
            get {
                return ResourceManager.GetString("DailyPNL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DashboardHeader0 {
            get {
                return ResourceManager.GetString("DashboardHeader0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics (Your company).
        /// </summary>
        public static string DashboardHeader1 {
            get {
                return ResourceManager.GetString("DashboardHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Volume ($).
        /// </summary>
        public static string DashboardHeader2 {
            get {
                return ResourceManager.GetString("DashboardHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Statistics (All Customers).
        /// </summary>
        public static string DashboardHeader3 {
            get {
                return ResourceManager.GetString("DashboardHeader3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Volume ($).
        /// </summary>
        public static string DashboardHeader4 {
            get {
                return ResourceManager.GetString("DashboardHeader4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal created successfully.
        /// </summary>
        public static string DealCreatedSuccessfully {
            get {
                return ResourceManager.GetString("DealCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal Summary &amp; Money transfer.
        /// </summary>
        public static string DealSummary {
            get {
                return ResourceManager.GetString("DealSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in a demo environment. Your trades won&apos;t have any effect!.
        /// </summary>
        public static string DemoEnvAlert {
            get {
                return ResourceManager.GetString("DemoEnvAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your Demo Account to a Real Account.
        /// </summary>
        public static string DemoEnvButtonTxt {
            get {
                return ResourceManager.GetString("DemoEnvButtonTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Company Details.
        /// </summary>
        public static string EditCompanyDetails {
            get {
                return ResourceManager.GetString("EditCompanyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User Details.
        /// </summary>
        public static string EditUserDetails {
            get {
                return ResourceManager.GetString("EditUserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Email.
        /// </summary>
        public static string Email2 {
            get {
                return ResourceManager.GetString("Email2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string EnterPrivateZone {
            get {
                return ResourceManager.GetString("EnterPrivateZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Bank Account information.
        /// </summary>
        public static string EnterTheBankAccountInformation {
            get {
                return ResourceManager.GetString("EnterTheBankAccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Company information.
        /// </summary>
        public static string EnterTheCompanyInformation {
            get {
                return ResourceManager.GetString("EnterTheCompanyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the User information.
        /// </summary>
        public static string EnterTheUserInformation {
            get {
                return ResourceManager.GetString("EnterTheUserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equity.
        /// </summary>
        public static string Equity {
            get {
                return ResourceManager.GetString("Equity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Estimation).
        /// </summary>
        public static string Estimation {
            get {
                return ResourceManager.GetString("Estimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euro €.
        /// </summary>
        public static string EUR {
            get {
                return ResourceManager.GetString("EUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EUR - ILS (€-₪).
        /// </summary>
        public static string EURILS {
            get {
                return ResourceManager.GetString("EURILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EUR - USD (€-$).
        /// </summary>
        public static string EURUSD {
            get {
                return ResourceManager.GetString("EURUSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange System.
        /// </summary>
        public static string ExchangeSystem {
            get {
                return ResourceManager.GetString("ExchangeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        public static string ExpiryDate {
            get {
                return ResourceManager.GetString("ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;FlatFX Bank Account Details:&lt;/h3&gt;
        ///        &lt;div&gt;
        ///            Bank Name: לאומי&lt;br /&gt;
        ///            Bank Number: 10&lt;br /&gt;
        ///            Branch Number: XXX&lt;br /&gt;
        ///            Account Number: XXXXXXXX&lt;br /&gt;
        ///            IBAN: IL99010XXX00000XXXXXXXX&lt;br /&gt;
        ///            Branch Address: Ben-gurion 12/15, Tel-Aviv&lt;br /&gt;
        ///        &lt;/div&gt;.
        /// </summary>
        public static string FlatFXBankAccountDetails {
            get {
                return ResourceManager.GetString("FlatFXBankAccountDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission.
        /// </summary>
        public static string FlatFXCommission {
            get {
                return ResourceManager.GetString("FlatFXCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string ForgotYourPassword {
            get {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from your bank account.
        /// </summary>
        public static string FromYourBankAccount {
            get {
                return ResourceManager.GetString("FromYourBankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GBP - ILS (£-₪).
        /// </summary>
        public static string GBPILS {
            get {
                return ResourceManager.GetString("GBPILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross P&amp;L.
        /// </summary>
        public static string GrossPNL {
            get {
                return ResourceManager.GetString("GrossPNL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here.
        /// </summary>
        public static string Here {
            get {
                return ResourceManager.GetString("Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporter / Importer / Currency converter ?.
        /// </summary>
        public static string HomeHeader1 {
            get {
                return ResourceManager.GetString("HomeHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bank charged large commissions? Know what is your exchange spread?.
        /// </summary>
        public static string HomeHeader2 {
            get {
                return ResourceManager.GetString("HomeHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop being a captive client - join the revolution in Forex.
        /// </summary>
        public static string HomeHeader3 {
            get {
                return ResourceManager.GetString("HomeHeader3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade directly with customers like you, on the mid price, skip your bank spreads.
        /// </summary>
        public static string HomeHeader4 {
            get {
                return ResourceManager.GetString("HomeHeader4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save up to 50,000 $ each year.
        /// </summary>
        public static string HomeHeader5 {
            get {
                return ResourceManager.GetString("HomeHeader5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Phone.
        /// </summary>
        public static string HomePhone {
            get {
                return ResourceManager.GetString("HomePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;How to transfer:&lt;/b&gt;&lt;br /&gt;
        ///            1) It is recommended to use your bank interent site in order to transfer money.&lt;br /&gt; 
        ///            2) If you want to transfer by sending fax to the bank:&lt;br /&gt;
        ///            &amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;in a few minutes an Email with the &quot;Money Transfer&quot; form will be send to you, please make sure all details are correct,&lt;br /&gt;
        ///            &amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;sign the form and send it to your bank, Fax no. 03-3333333.&lt;br /&gt;
        ///            You can follow th [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HowToTransfer {
            get {
                return ResourceManager.GetString("HowToTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN.
        /// </summary>
        public static string IBAN {
            get {
                return ResourceManager.GetString("IBAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Israeli new sheqel ₪.
        /// </summary>
        public static string ILS {
            get {
                return ResourceManager.GetString("ILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of.
        /// </summary>
        public static string InAmount {
            get {
                return ResourceManager.GetString("InAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite co-worker to join your company.
        /// </summary>
        public static string InviteCoWorker1 {
            get {
                return ResourceManager.GetString("InviteCoWorker1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Warning: The co-worker will be able to join the company and execute deals within the site.
        /// </summary>
        public static string InviteCoWorker2 {
            get {
                return ResourceManager.GetString("InviteCoWorker2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvoiceCurrency.
        /// </summary>
        public static string InvoiceCurrency {
            get {
                return ResourceManager.GetString("InvoiceCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is default?.
        /// </summary>
        public static string IsDefaultAccount {
            get {
                return ResourceManager.GetString("IsDefaultAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Demo Account.
        /// </summary>
        public static string IsDemoAccount {
            get {
                return ResourceManager.GetString("IsDemoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is deposit valid.
        /// </summary>
        public static string IsDepositValid {
            get {
                return ResourceManager.GetString("IsDepositValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is sign on registration agreement.
        /// </summary>
        public static string IsSignOnRegistrationAgreement {
            get {
                return ResourceManager.GetString("IsSignOnRegistrationAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join the Revolution.
        /// </summary>
        public static string JoinTheRevolution {
            get {
                return ResourceManager.GetString("JoinTheRevolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPY - ILS (¥-₪).
        /// </summary>
        public static string JPYILS {
            get {
                return ResourceManager.GetString("JPYILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Update.
        /// </summary>
        public static string LastUpdate {
            get {
                return ResourceManager.GetString("LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Amount.
        /// </summary>
        public static string MaxAmount {
            get {
                return ResourceManager.GetString("MaxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string MenuActions {
            get {
                return ResourceManager.GetString("MenuActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How It Works.
        /// </summary>
        public static string MenuHowItWorks {
            get {
                return ResourceManager.GetString("MenuHowItWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie.
        /// </summary>
        public static string MenuMovie {
            get {
                return ResourceManager.GetString("MenuMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mid Rate.
        /// </summary>
        public static string MidRate {
            get {
                return ResourceManager.GetString("MidRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Amount.
        /// </summary>
        public static string MinAmount {
            get {
                return ResourceManager.GetString("MinAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal partner execution amount.
        /// </summary>
        public static string MinimalPartnerExecutionAmount {
            get {
                return ResourceManager.GetString("MinimalPartnerExecutionAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal partner total volume (USD).
        /// </summary>
        public static string MinimalPartnerTotalVolumeUSD {
            get {
                return ResourceManager.GetString("MinimalPartnerTotalVolumeUSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone.
        /// </summary>
        public static string MobilePhone {
            get {
                return ResourceManager.GetString("MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Mobile Phone.
        /// </summary>
        public static string MobilePhone2 {
            get {
                return ResourceManager.GetString("MobilePhone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Transfer Instractions.
        /// </summary>
        public static string MoneyTransferInstractions {
            get {
                return ResourceManager.GetString("MoneyTransferInstractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Deals.
        /// </summary>
        public static string NumOfDeals {
            get {
                return ResourceManager.GetString("NumOfDeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string OfCurrency {
            get {
                return ResourceManager.GetString("OfCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Phone.
        /// </summary>
        public static string OfficePhone {
            get {
                return ResourceManager.GetString("OfficePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional  Office Phone.
        /// </summary>
        public static string OfficePhone2 {
            get {
                return ResourceManager.GetString("OfficePhone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once the money will be transfered, FlatFX will transfer.
        /// </summary>
        public static string OnceTheMoney {
            get {
                return ResourceManager.GetString("OnceTheMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Line Rates.
        /// </summary>
        public static string OnLineRates {
            get {
                return ResourceManager.GetString("OnLineRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Book.
        /// </summary>
        public static string OrderBook {
            get {
                return ResourceManager.GetString("OrderBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mid Rate - .
        /// </summary>
        public static string OrderBookRate2 {
            get {
                return ResourceManager.GetString("OrderBookRate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Currency pair.
        /// </summary>
        public static string OrderChooseCurrencyPair {
            get {
                return ResourceManager.GetString("OrderChooseCurrencyPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Created Successfully.
        /// </summary>
        public static string OrderCreatedSuccessfully {
            get {
                return ResourceManager.GetString("OrderCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new Order.
        /// </summary>
        public static string OrderHeader {
            get {
                return ResourceManager.GetString("OrderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID.
        /// </summary>
        public static string OrderID {
            get {
                return ResourceManager.GetString("OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to perform the Order.
        /// </summary>
        public static string OrderNotAllowed {
            get {
                return ResourceManager.GetString("OrderNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wants to find a partner for exchanging on the Mid price (no spreads) ? &lt;br /&gt;Create new order on the Mid rate, &lt;u&gt;no spread&lt;/u&gt;, the commission is always 0.2% instead of 1.1% in the banks..
        /// </summary>
        public static string OrderRemark {
            get {
                return ResourceManager.GetString("OrderRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Order currencies, required spread, amount, buy/sell, bank account, ....
        /// </summary>
        public static string OrderStep1Desc {
            get {
                return ResourceManager.GetString("OrderStep1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Order details.
        /// </summary>
        public static string OrderStep1Header {
            get {
                return ResourceManager.GetString("OrderStep1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See your Order details and confirm the Order.
        /// </summary>
        public static string OrderStep2Desc {
            get {
                return ResourceManager.GetString("OrderStep2Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your Order.
        /// </summary>
        public static string OrderStep2Header {
            get {
                return ResourceManager.GetString("OrderStep2Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See the Order summary.
        /// </summary>
        public static string OrderStep3Desc {
            get {
                return ResourceManager.GetString("OrderStep3Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Summary.
        /// </summary>
        public static string OrderStep3Header {
            get {
                return ResourceManager.GetString("OrderStep3Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit your Order.
        /// </summary>
        public static string OrderSubmit1 {
            get {
                return ResourceManager.GetString("OrderSubmit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit your DEMO Order.
        /// </summary>
        public static string OrderSubmitDemo {
            get {
                return ResourceManager.GetString("OrderSubmitDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Summary.
        /// </summary>
        public static string OrderSummary {
            get {
                return ResourceManager.GetString("OrderSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can edit or cancel your orders.
        /// </summary>
        public static string OrderSummary1 {
            get {
                return ResourceManager.GetString("OrderSummary1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order System.
        /// </summary>
        public static string OrderSystem {
            get {
                return ResourceManager.GetString("OrderSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pair.
        /// </summary>
        public static string Pair {
            get {
                return ResourceManager.GetString("Pair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner.
        /// </summary>
        public static string Partner {
            get {
                return ResourceManager.GetString("Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please transfer.
        /// </summary>
        public static string PleaseTransfer {
            get {
                return ResourceManager.GetString("PleaseTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        public static string Provider {
            get {
                return ResourceManager.GetString("Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Accounts.
        /// </summary>
        public static string ProviderAccounts {
            get {
                return ResourceManager.GetString("ProviderAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider/Bank.
        /// </summary>
        public static string ProviderOrBank {
            get {
                return ResourceManager.GetString("ProviderOrBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Providers.
        /// </summary>
        public static string Providers {
            get {
                return ResourceManager.GetString("Providers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Account.
        /// </summary>
        public static string RegisterAccount {
            get {
                return ResourceManager.GetString("RegisterAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        public static string RegisterAsNewUser {
            get {
                return ResourceManager.GetString("RegisterAsNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Company.
        /// </summary>
        public static string RegisterCompany {
            get {
                return ResourceManager.GetString("RegisterCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register User.
        /// </summary>
        public static string RegisterUser {
            get {
                return ResourceManager.GetString("RegisterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Amount.
        /// </summary>
        public static string SelectAmount {
            get {
                return ResourceManager.GetString("SelectAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select pair.
        /// </summary>
        public static string SelectPair {
            get {
                return ResourceManager.GetString("SelectPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Required Spread (Mid + Promil).
        /// </summary>
        public static string SelectRequiredSpread {
            get {
                return ResourceManager.GetString("SelectRequiredSpread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        public static string Sell {
            get {
                return ResourceManager.GetString("Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        public static string Sell2 {
            get {
                return ResourceManager.GetString("Sell2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Amount (you give).
        /// </summary>
        public static string SellAmount {
            get {
                return ResourceManager.GetString("SellAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settlement Date.
        /// </summary>
        public static string SettlementDate {
            get {
                return ResourceManager.GetString("SettlementDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mid rate according to.
        /// </summary>
        public static string ShowRateRemarksRow1 {
            get {
                return ResourceManager.GetString("ShowRateRemarksRow1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last update date:.
        /// </summary>
        public static string ShowRateRemarksRow2 {
            get {
                return ResourceManager.GetString("ShowRateRemarksRow2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buying rate: The rate that the site is buying the currency from the customer.
        /// </summary>
        public static string ShowRateRemarksRow3 {
            get {
                return ResourceManager.GetString("ShowRateRemarksRow3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selling rate: The rate that the site is selling the currency to the customer.
        /// </summary>
        public static string ShowRateRemarksRow4 {
            get {
                return ResourceManager.GetString("ShowRateRemarksRow4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mid rate: The inter bank trading rate during trading time.
        /// </summary>
        public static string ShowRateRemarksRow5 {
            get {
                return ResourceManager.GetString("ShowRateRemarksRow5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing Key.
        /// </summary>
        public static string SigningKey {
            get {
                return ResourceManager.GetString("SigningKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string Signout {
            get {
                return ResourceManager.GetString("Signout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Book.
        /// </summary>
        public static string SlideHeader1 {
            get {
                return ResourceManager.GetString("SlideHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SlideHeader10 {
            get {
                return ResourceManager.GetString("SlideHeader10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Order.
        /// </summary>
        public static string SlideHeader2 {
            get {
                return ResourceManager.GetString("SlideHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Deals.
        /// </summary>
        public static string SlideHeader3 {
            get {
                return ResourceManager.GetString("SlideHeader3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View your Statistics.
        /// </summary>
        public static string SlideHeader4 {
            get {
                return ResourceManager.GetString("SlideHeader4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Deal.
        /// </summary>
        public static string SlideHeader5 {
            get {
                return ResourceManager.GetString("SlideHeader5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal Confirmation.
        /// </summary>
        public static string SlideHeader6 {
            get {
                return ResourceManager.GetString("SlideHeader6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnLine Rates.
        /// </summary>
        public static string SlideHeader7 {
            get {
                return ResourceManager.GetString("SlideHeader7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading Room.
        /// </summary>
        public static string SlideHeader8 {
            get {
                return ResourceManager.GetString("SlideHeader8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string SlideHeader9 {
            get {
                return ResourceManager.GetString("SlideHeader9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find an order that best match your currency exchange requirements.
        /// </summary>
        public static string SlideText1 {
            get {
                return ResourceManager.GetString("SlideText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SlideText10 {
            get {
                return ResourceManager.GetString("SlideText10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new currency exchange order and wait for other site user to match your order.
        /// </summary>
        public static string SlideText2 {
            get {
                return ResourceManager.GetString("SlideText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your deals &amp; orders. edit, cancel and explore.
        /// </summary>
        public static string SlideText3 {
            get {
                return ResourceManager.GetString("SlideText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View your total volume, today volume, total savings, charts, ....
        /// </summary>
        public static string SlideText4 {
            get {
                return ResourceManager.GetString("SlideText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a deal to be performed immediately against FlatFX prices.
        /// </summary>
        public static string SlideText5 {
            get {
                return ResourceManager.GetString("SlideText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your deal price and deal commission.
        /// </summary>
        public static string SlideText6 {
            get {
                return ResourceManager.GetString("SlideText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See online rates and compare FlatFX prices with your bank prices.
        /// </summary>
        public static string SlideText7 {
            get {
                return ResourceManager.GetString("SlideText7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are invited to visit our office at ....
        /// </summary>
        public static string SlideText8 {
            get {
                return ResourceManager.GetString("SlideText8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are invited to visit our office at ....
        /// </summary>
        public static string SlideText9 {
            get {
                return ResourceManager.GetString("SlideText9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Deal Request.
        /// </summary>
        public static string SmplTradeOrderHeader {
            get {
                return ResourceManager.GetString("SmplTradeOrderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to perform the currency exchange.
        /// </summary>
        public static string SmplTradeOrderNotAllowed {
            get {
                return ResourceManager.GetString("SmplTradeOrderNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit your Deal.
        /// </summary>
        public static string SmplTradeOrderSubmit {
            get {
                return ResourceManager.GetString("SmplTradeOrderSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit your DEMO Deal.
        /// </summary>
        public static string SmplTradeOrderSubmitDemo {
            get {
                return ResourceManager.GetString("SmplTradeOrderSubmitDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The funds must received by FlatFX on.
        /// </summary>
        public static string SmplTradeOrderTheFundsMust {
            get {
                return ResourceManager.GetString("SmplTradeOrderTheFundsMust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I wish to.
        /// </summary>
        public static string SmplTradeOrderWishTo {
            get {
                return ResourceManager.GetString("SmplTradeOrderWishTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter currencies, amount, buy/sell, bank account, ....
        /// </summary>
        public static string SmplTradeStep1Desc {
            get {
                return ResourceManager.GetString("SmplTradeStep1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Deal details.
        /// </summary>
        public static string SmplTradeStep1Header {
            get {
                return ResourceManager.GetString("SmplTradeStep1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See the live rates and confirm the deal.
        /// </summary>
        public static string SmplTradeStep2Desc {
            get {
                return ResourceManager.GetString("SmplTradeStep2Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Deal.
        /// </summary>
        public static string SmplTradeStep2Header {
            get {
                return ResourceManager.GetString("SmplTradeStep2Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See the Deal summary and the &quot;money transfer&quot; instractions.
        /// </summary>
        public static string SmplTradeStep3Desc {
            get {
                return ResourceManager.GetString("SmplTradeStep3Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Transfer.
        /// </summary>
        public static string SmplTradeStep3Header {
            get {
                return ResourceManager.GetString("SmplTradeStep3Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spread Required.
        /// </summary>
        public static string SpreadRequired {
            get {
                return ResourceManager.GetString("SpreadRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        public static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still don&apos;t have an account?.
        /// </summary>
        public static string StillDontHaveAccount {
            get {
                return ResourceManager.GetString("StillDontHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWIFT.
        /// </summary>
        public static string SWIFT {
            get {
                return ResourceManager.GetString("SWIFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The funds must received by FlatFX on.
        /// </summary>
        public static string TheFunds {
            get {
                return ResourceManager.GetString("TheFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today Volume.
        /// </summary>
        public static string TodayVolume {
            get {
                return ResourceManager.GetString("TodayVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Savings.
        /// </summary>
        public static string TotalSavings {
            get {
                return ResourceManager.GetString("TotalSavings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Volume.
        /// </summary>
        public static string TotalVolume {
            get {
                return ResourceManager.GetString("TotalVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Dollar $.
        /// </summary>
        public static string USD {
            get {
                return ResourceManager.GetString("USD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD - ILS ($-₪).
        /// </summary>
        public static string USDILS {
            get {
                return ResourceManager.GetString("USDILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log in.
        /// </summary>
        public static string UseLocalLogin {
            get {
                return ResourceManager.GetString("UseLocalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string UserComfirmPasswordValidation {
            get {
                return ResourceManager.GetString("UserComfirmPasswordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Created Successfully.
        /// </summary>
        public static string UserCreatedSuccessfully {
            get {
                return ResourceManager.GetString("UserCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Emails to email addresses.
        /// </summary>
        public static string UserList_SendEmail {
            get {
                return ResourceManager.GetString("UserList_SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Invoice to email addresses.
        /// </summary>
        public static string UserList_SendInvoice {
            get {
                return ResourceManager.GetString("UserList_SendInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Manage.
        /// </summary>
        public static string UserManage {
            get {
                return ResourceManager.GetString("UserManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///        Thank you for registering for FlatFX.
        ///    &lt;/p&gt;
        ///    &lt;p&gt;
        ///        An Email Confirmation will be send to your email address during the next minutes,&lt;br /&gt;
        ///        Please click on the relevant link in order to activate your account.&lt;br /&gt;
        ///        Wishing you a giant saving,&lt;br /&gt;
        ///        FlatFX Team.
        ///    &lt;/p&gt;.
        /// </summary>
        public static string UserRegisteredSucceeded {
            get {
                return ResourceManager.GetString("UserRegisteredSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be {2}-{1} characters long..
        /// </summary>
        public static string ValidationLength {
            get {
                return ResourceManager.GetString("ValidationLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        public static string ValidationRequired {
            get {
                return ResourceManager.GetString("ValidationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid IP.
        /// </summary>
        public static string ValidIP {
            get {
                return ResourceManager.GetString("ValidIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Site.
        /// </summary>
        public static string WebSite {
            get {
                return ResourceManager.GetString("WebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We Traded At.
        /// </summary>
        public static string WeTradedAt {
            get {
                return ResourceManager.GetString("WeTradedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must confirm your Email in order to activate your account.
        /// </summary>
        public static string YouMustConfirmYourEmail {
            get {
                return ResourceManager.GetString("YouMustConfirmYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Rate Was.
        /// </summary>
        public static string YourRateWas {
            get {
                return ResourceManager.GetString("YourRateWas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Saving:.
        /// </summary>
        public static string YourSaving {
            get {
                return ResourceManager.GetString("YourSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Save.
        /// </summary>
        public static string YouSave {
            get {
                return ResourceManager.GetString("YouSave", resourceCulture);
            }
        }
    }
}
