//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlatFXResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlatFXResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account full name.
        /// </summary>
        public static string AccountFullName {
            get {
                return ResourceManager.GetString("AccountFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name.
        /// </summary>
        public static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        public static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow to trade directlly.
        /// </summary>
        public static string AllowToTradeDirectlly {
            get {
                return ResourceManager.GetString("AllowToTradeDirectlly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved by FlatFX.
        /// </summary>
        public static string ApprovedBYFlatFX {
            get {
                return ResourceManager.GetString("ApprovedBYFlatFX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved by provider.
        /// </summary>
        public static string ApprovedBYProvider {
            get {
                return ResourceManager.GetString("ApprovedBYProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        public static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank account details.
        /// </summary>
        public static string BankAccountDetails {
            get {
                return ResourceManager.GetString("BankAccountDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Number.
        /// </summary>
        public static string BranchNumber {
            get {
                return ResourceManager.GetString("BranchNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Phone.
        /// </summary>
        public static string CarPhone {
            get {
                return ResourceManager.GetString("CarPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string CompanyFullName {
            get {
                return ResourceManager.GetString("CompanyFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Name.
        /// </summary>
        public static string CompanyShortName {
            get {
                return ResourceManager.GetString("CompanyShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Volume (yearly, USD).
        /// </summary>
        public static string CompanyVolumePerYearUSD {
            get {
                return ResourceManager.GetString("CompanyVolumePerYearUSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Details.
        /// </summary>
        public static string ContactDetails {
            get {
                return ResourceManager.GetString("ContactDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created At.
        /// </summary>
        public static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new account group.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new company.
        /// </summary>
        public static string CreateNewCompany {
            get {
                return ResourceManager.GetString("CreateNewCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new user.
        /// </summary>
        public static string CreateNewUser {
            get {
                return ResourceManager.GetString("CreateNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Type.
        /// </summary>
        public static string CustomerType {
            get {
                return ResourceManager.GetString("CustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily P&amp;L.
        /// </summary>
        public static string DailyPNL {
            get {
                return ResourceManager.GetString("DailyPNL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Email.
        /// </summary>
        public static string Email2 {
            get {
                return ResourceManager.GetString("Email2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equity.
        /// </summary>
        public static string Equity {
            get {
                return ResourceManager.GetString("Equity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross P&amp;L.
        /// </summary>
        public static string GrossPNL {
            get {
                return ResourceManager.GetString("GrossPNL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Phone.
        /// </summary>
        public static string HomePhone {
            get {
                return ResourceManager.GetString("HomePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN.
        /// </summary>
        public static string IBAN {
            get {
                return ResourceManager.GetString("IBAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvoiceCurrency.
        /// </summary>
        public static string InvoiceCurrency {
            get {
                return ResourceManager.GetString("InvoiceCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is default?.
        /// </summary>
        public static string IsDefaultAccount {
            get {
                return ResourceManager.GetString("IsDefaultAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Demo Account.
        /// </summary>
        public static string IsDemoAccount {
            get {
                return ResourceManager.GetString("IsDemoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is deposit valid.
        /// </summary>
        public static string IsDepositValid {
            get {
                return ResourceManager.GetString("IsDepositValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is sign on registration agreement.
        /// </summary>
        public static string IsSignOnRegistrationAgreement {
            get {
                return ResourceManager.GetString("IsSignOnRegistrationAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string MenuActions {
            get {
                return ResourceManager.GetString("MenuActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How It Works.
        /// </summary>
        public static string MenuHowItWorks {
            get {
                return ResourceManager.GetString("MenuHowItWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie.
        /// </summary>
        public static string MenuMovie {
            get {
                return ResourceManager.GetString("MenuMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone.
        /// </summary>
        public static string MobilePhone {
            get {
                return ResourceManager.GetString("MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Mobile Phone.
        /// </summary>
        public static string MobilePhone2 {
            get {
                return ResourceManager.GetString("MobilePhone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Phone.
        /// </summary>
        public static string OfficePhone {
            get {
                return ResourceManager.GetString("OfficePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional  Office Phone.
        /// </summary>
        public static string OfficePhone2 {
            get {
                return ResourceManager.GetString("OfficePhone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider/Bank.
        /// </summary>
        public static string ProviderOrBank {
            get {
                return ResourceManager.GetString("ProviderOrBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        public static string RegisterAsNewUser {
            get {
                return ResourceManager.GetString("RegisterAsNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing Key.
        /// </summary>
        public static string SigningKey {
            get {
                return ResourceManager.GetString("SigningKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string Signout {
            get {
                return ResourceManager.GetString("Signout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWIFT.
        /// </summary>
        public static string SWIFT {
            get {
                return ResourceManager.GetString("SWIFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log in.
        /// </summary>
        public static string UseLocalLogin {
            get {
                return ResourceManager.GetString("UseLocalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string UserComfirmPasswordValidation {
            get {
                return ResourceManager.GetString("UserComfirmPasswordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Emails to email addresses.
        /// </summary>
        public static string UserList_SendEmail {
            get {
                return ResourceManager.GetString("UserList_SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Invoice to email addresses.
        /// </summary>
        public static string UserList_SendInvoice {
            get {
                return ResourceManager.GetString("UserList_SendInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string ValidationLength {
            get {
                return ResourceManager.GetString("ValidationLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        public static string ValidationRequired {
            get {
                return ResourceManager.GetString("ValidationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid IP.
        /// </summary>
        public static string ValidIP {
            get {
                return ResourceManager.GetString("ValidIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Site.
        /// </summary>
        public static string WebSite {
            get {
                return ResourceManager.GetString("WebSite", resourceCulture);
            }
        }
    }
}
